"""
Django settings for CFEhome project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from decouple import config

# Cast "True"/"1" to a Python boolean
DEBUG = config("DJANGO_DEBUG", default=False, cast=bool)

# If DJANGO_SECRET_KEY is missing, decauple raises an UndefinedValueError
SECRET_KEY = config("DJANGO_SECRET_KEY")

STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default=None)
STRIPE_PUB_KEY = config("STRIPE_PUB_KEY", default=None)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/


ALLOWED_HOSTS = [
    ".railway.app",
    "127.0.0.1",
    "localhost",
]

# django-allauth 
# Tells Django how to check credentials
AUTHENTICATION_BACKENDS = [ 
    'django.contrib.auth.backends.ModelBackend',  #default username/password
    'allauth.account.auth_backends.AuthenticationBackend', 
]

SOCIALACCOUNT_PROVIDERS = {
    'github': {
        'VERIFIED_EMAIL': True
    }
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', # Admin panel interface
    'django.contrib.auth', # User authentication & permissions
    'django.contrib.contenttypes', # Content type system
    'django.contrib.sessions', # Session management
    'django.contrib.messages', # Flash messaging
    'django.contrib.staticfiles', #Static file management
    'django.contrib.sites',

    # Custom Apps
    'visits',
    'Commando',
    'off',

    # django-allauth-ui
    'allauth_ui',
    
    # django-allauth
    # (Built-in Allauth Apps), registers allauth's apps so Django finds their models, templates, and views
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'widget_tweaks',
    'slippers',
    'subscriptions',
    'customers',
    'checkouts',
]

SITE_ID = 1
ALLAUTH_UI_THEME = "light"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware', #django-allauth
]

# Allauth Behavior Settings
ACCOUNT_LOGIN_METHODS = {"username", "email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password1*"]
ACCOUNT_EMAIL_VERIFICATION = 'mandatory' # Forces users to verify email before logging in
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

ROOT_URLCONF = 'CFEhome.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CFEhome.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static_files',
]

STATIC_ROOT = BASE_DIR.parent / 'local_cdn'

# Django 4.2+ Storage Engine format
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "CFEhome.storage.CustomStaticFilesStorage",
    },
}

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
        'OPTIONS': {
            'host': config("EMAIL_HOST", default="smtp.gmail.com"),
            'port': config("EMAIL_PORT", default=587, cast=int),
            'username': config('EMAIL_HOST_USER', default=""),
            'password': config('EMAIL_HOST_PASSWORD', default=""),
            'use_tls': config("EMAIL_USE_TLS", default=True, cast=bool),
        },
    },
}


# Optional Admin alert recipients
ADMINS = [("Admin", "felix.mengesa.dev@gmail.com")]
MANAGERS = ADMINS

DATABASE_URL = config("DATABASE_URL", default=None)

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=0,
            conn_health_checks=True, #Verifies active connections
        )
    }
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
else:
    # Fallback to SQLite if DATABASE_URL is not set
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }