# Generated by Django 6.1.1 on 2026-10-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('permissions', models.ManyToManyField(limit_choices_to={'content_type_app_label': 'subscriptions'}, to='auth.permission')),
            ],
            options={
                'permissions': [('basic_perm', 'Basic Plan Permission'), ('pro_perm', 'Pro Plan Permission'), ('advanced_perm', 'Advanced Plan Permission')],
            },
        ),
    ]
